version: "3.8"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      PGUSER: acmeuser
      POSTGRES_PASSWORD: acme1234
      POSTGRES_USER: acmeuser
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend
  adminer:
    image: adminer:standalone
    restart: always
    ports:
    - 8082:8080
  flyway:
    image: flyway/flyway:latest-alpine
    command: -url=jdbc:postgresql://postgres:5432/acmeuser -user=acmeuser -password=acme1234 -connectRetries=60 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - postgres
    networks:
      - backend
  acmepools:
    image: acmepools
    environment:
      - DB_NAME=acmeuser
      - DB_USER=acmeuser
      - DB_PASSWORD=acme1234
      - DB_PORT=5432
      - DOCKER_HOST=postgres
    build:
      context: .
    ports:
      - "8092:8080"
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
  frontend:
